In [2]:
import pandas as py
product=py.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\02_Raw_Data\Product_Information.csv")
print(product.to_string())

   Product ID         Product Name     Category  Subcategory  Unit Cost  Unit Price     Supplier  Shelf Life
0    PRD10000        Cheese Item 0        Dairy       Cheese     127.63      143.90   Supplier 1          12
1    PRD10001         Bread Item 1       Bakery        Bread     422.83      570.20   Supplier 4          37
2    PRD10002   Accessories Item 2  Electronics  Accessories      74.91      110.80   Supplier 8          70
3    PRD10003           Men Item 3      Apparel          Men     310.83      461.74   Supplier 2          46
4    PRD10004           Men Item 4      Apparel          Men     297.77      438.18  Supplier 10         178
5    PRD10005        Laptop Item 5  Electronics       Laptop     471.91      556.54  Supplier 10         165
6    PRD10006         Bread Item 6       Bakery        Bread     354.65      432.90  Supplier 10          35
7    PRD10007        Cheese Item 7        Dairy       Cheese     275.72      376.25   Supplier 2         134
8    PRD10008           Men Item 8      Apparel          Men     427.80      611.30   Supplier 2         115
9    PRD10009          Kids Item 9      Apparel         Kids     447.96      575.13   Supplier 3         116
10   PRD10010      Cookies Item 10       Bakery      Cookies     270.44      367.85  Supplier 10         142
11   PRD10011       Laptop Item 11  Electronics       Laptop     229.08      318.97   Supplier 5          87
12   PRD10012        Bread Item 12       Bakery        Bread     153.89      197.03   Supplier 8         150
13   PRD10013       Laptop Item 13  Electronics       Laptop      33.78       48.66   Supplier 3         129
14   PRD10014        Cakes Item 14       Bakery        Cakes     402.96      498.11  Supplier 10          75
15   PRD10015       Yogurt Item 15        Dairy       Yogurt     475.07      538.85   Supplier 7         130
16   PRD10016      Cookies Item 16       Bakery      Cookies     248.52      344.13   Supplier 8           9
17   PRD10017       Cheese Item 17        Dairy       Cheese     126.37      173.98   Supplier 5         174
18   PRD10018        Women Item 18      Apparel        Women     285.67      353.52   Supplier 9          89
19   PRD10019         Kids Item 19      Apparel         Kids     237.80      290.75   Supplier 4          35
20   PRD10020        Cakes Item 20       Bakery        Cakes      77.39      101.72   Supplier 3          54
21   PRD10021      Cookies Item 21       Bakery      Cookies     252.42      350.82   Supplier 9         157
22   PRD10022          Men Item 22      Apparel          Men     419.66      511.36   Supplier 6          50
23   PRD10023          Men Item 23      Apparel          Men     359.85      414.06   Supplier 1          18
24   PRD10024         Kids Item 24      Apparel         Kids     473.16      641.20   Supplier 8          31
25   PRD10025       Yogurt Item 25        Dairy       Yogurt     156.48      202.09   Supplier 6          52
26   PRD10026       Cheese Item 26        Dairy       Cheese     471.71      609.02   Supplier 2         107
27   PRD10027       Mobile Item 27  Electronics       Mobile     296.97      408.21   Supplier 3          43
28   PRD10028          Men Item 28      Apparel          Men     497.08      570.34   Supplier 7         160
29   PRD10029      Cookies Item 29       Bakery      Cookies     202.58      296.46   Supplier 5         155
30   PRD10030       Laptop Item 30  Electronics       Laptop     292.94      329.29   Supplier 2          58
31   PRD10031        Cakes Item 31       Bakery        Cakes     337.01      391.88   Supplier 3         146
32   PRD10032         Milk Item 32        Dairy         Milk      21.28       27.24  Supplier 10         125
33   PRD10033          Men Item 33      Apparel          Men     131.11      181.30   Supplier 8          23
34   PRD10034        Cakes Item 34       Bakery        Cakes     398.16      537.53   Supplier 4         113
35   PRD10035       Yogurt Item 35        Dairy       Yogurt     127.91      148.32   Supplier 5          41
36   PRD10036         Milk Item 36        Dairy         Milk      99.64      121.86  Supplier 10          78
37   PRD10037       Mobile Item 37  Electronics       Mobile     244.98      299.28   Supplier 7          74
38   PRD10038       Laptop Item 38  Electronics       Laptop      58.61       65.41   Supplier 7          87
39   PRD10039          Men Item 39      Apparel          Men      63.84       94.79  Supplier 10         155
40   PRD10040       Yogurt Item 40        Dairy       Yogurt     414.28      551.20   Supplier 3         125
41   PRD10041       Laptop Item 41  Electronics       Laptop     107.11      142.90   Supplier 8          28
42   PRD10042       Laptop Item 42  Electronics       Laptop     216.01      265.35   Supplier 2          46
43   PRD10043        Women Item 43      Apparel        Women     352.96      428.95   Supplier 7         145
44   PRD10044       Cheese Item 44        Dairy       Cheese      62.27       74.78   Supplier 2         108
45   PRD10045       Yogurt Item 45        Dairy       Yogurt     437.30      561.84   Supplier 1          53
46   PRD10046         Kids Item 46      Apparel         Kids     383.09      517.23   Supplier 1          57
47   PRD10047         Kids Item 47      Apparel         Kids      82.89      100.73   Supplier 8          36
48   PRD10048       Yogurt Item 48        Dairy       Yogurt     312.26      373.38   Supplier 3          84
49   PRD10049       Yogurt Item 49        Dairy       Yogurt     215.84      256.82   Supplier 2         123
50   PRD10050       Yogurt Item 50        Dairy       Yogurt     419.43      544.99   Supplier 5         135
51   PRD10051        Women Item 51      Apparel        Women     420.67      627.68   Supplier 4         121
52   PRD10052        Cakes Item 52       Bakery        Cakes     111.49      149.37   Supplier 3          22
53   PRD10053        Women Item 53      Apparel        Women     183.14      259.16   Supplier 5           5
54   PRD10054         Kids Item 54      Apparel         Kids     163.31      217.98   Supplier 8          43
55   PRD10055  Accessories Item 55  Electronics  Accessories     252.48      311.30   Supplier 9         101
56   PRD10056       Laptop Item 56  Electronics       Laptop     437.41      652.75   Supplier 4         151
57   PRD10057       Mobile Item 57  Electronics       Mobile     430.89      544.78   Supplier 6         126
58   PRD10058       Laptop Item 58  Electronics       Laptop     494.44      700.60   Supplier 3         131
59   PRD10059         Milk Item 59        Dairy         Milk     261.10      348.85   Supplier 2         117
60   PRD10060       Yogurt Item 60        Dairy       Yogurt     457.01      505.52   Supplier 3         109
61   PRD10061        Bread Item 61       Bakery        Bread     245.36      365.02   Supplier 6         164
62   PRD10062  Accessories Item 62  Electronics  Accessories      58.55       72.10   Supplier 9         102
63   PRD10063         Kids Item 63      Apparel         Kids     364.98      512.34   Supplier 9          14
64   PRD10064         Milk Item 64        Dairy         Milk     322.96      474.23   Supplier 4          28
65   PRD10065       Mobile Item 65  Electronics       Mobile     384.98      531.87   Supplier 2         118
66   PRD10066      Cookies Item 66       Bakery      Cookies     163.74      182.01   Supplier 6          19
67   PRD10067        Women Item 67      Apparel        Women     199.92      231.55   Supplier 9         110
68   PRD10068        Bread Item 68       Bakery        Bread     104.03      139.80   Supplier 7         163
69   PRD10069        Cakes Item 69       Bakery        Cakes     458.16      530.20   Supplier 8         168
70   PRD10070        Women Item 70      Apparel        Women     142.56      157.35   Supplier 8          78
71   PRD10071        Bread Item 71       Bakery        Bread     232.03      287.31  Supplier 10          81
72   PRD10072  Accessories Item 72  Electronics  Accessories     140.05      201.41   Supplier 4         103
73   PRD10073       Mobile Item 73  Electronics       Mobile     133.86      177.87  Supplier 10          80
74   PRD10074          Men Item 74      Apparel          Men     489.41      667.21   Supplier 5           7
75   PRD10075       Yogurt Item 75        Dairy       Yogurt     377.68      541.27   Supplier 5          63
76   PRD10076          Men Item 76      Apparel          Men     325.58      439.00   Supplier 3         165
77   PRD10077       Yogurt Item 77        Dairy       Yogurt     330.24      404.07   Supplier 8          13
78   PRD10078         Kids Item 78      Apparel         Kids      83.08      121.62   Supplier 6         111
79   PRD10079        Bread Item 79       Bakery        Bread      83.44      109.79   Supplier 6         140
80   PRD10080          Men Item 80      Apparel          Men     143.35      204.97   Supplier 8          80
81   PRD10081          Men Item 81      Apparel          Men     244.80      276.65   Supplier 4         178
82   PRD10082  Accessories Item 82  Electronics  Accessories     195.57      276.98   Supplier 1          72
83   PRD10083       Cheese Item 83        Dairy       Cheese     196.92      275.61   Supplier 5         154
84   PRD10084  Accessories Item 84  Electronics  Accessories     471.34      538.90   Supplier 4         125
85   PRD10085       Yogurt Item 85        Dairy       Yogurt     444.43      588.68  Supplier 10          61
86   PRD10086       Yogurt Item 86        Dairy       Yogurt     415.45      608.12   Supplier 5         171
87   PRD10087       Mobile Item 87  Electronics       Mobile      87.09      128.76   Supplier 5         131
88   PRD10088         Milk Item 88        Dairy         Milk     132.70      174.50   Supplier 7         121
89   PRD10089         Kids Item 89      Apparel         Kids     475.70      655.80   Supplier 9         112
90   PRD10090        Cakes Item 90       Bakery        Cakes     334.36      479.30  Supplier 10         109
91   PRD10091          Men Item 91      Apparel          Men     351.33      417.00   Supplier 8          65
92   PRD10092          Men Item 92      Apparel          Men     490.85      612.06   Supplier 6          20
93   PRD10093       Laptop Item 93  Electronics       Laptop     111.11      127.65   Supplier 8          28
94   PRD10094      Cookies Item 94       Bakery      Cookies     326.96      486.66   Supplier 1          90
95   PRD10095        Bread Item 95       Bakery        Bread     397.75      470.17   Supplier 9          58
96   PRD10096        Bread Item 96       Bakery        Bread     177.71      205.97  Supplier 10           5
97   PRD10097          Men Item 97      Apparel          Men     494.01      650.16   Supplier 3          33
98   PRD10098         Milk Item 98        Dairy         Milk      27.13       38.42   Supplier 4         155
99   PRD10099          Men Item 99      Apparel          Men     103.64      116.18   Supplier 7         139

In [4]:
product.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    100 non-null    str
 1   Product Name  100 non-null    str
 2   Category      100 non-null    str
 3   Subcategory   100 non-null    str
 4   Unit Cost     100 non-null    float64
 5   Unit Price    100 non-null    float64
 6   Supplier      100 non-null    str
 7   Shelf Life    100 non-null    int64
dtypes: float64(2), int64(1), str(5)
memory usage: 6.4 KB

In [3]:

product.shape

(100, 8)

In [4]:
product.describe()

       Unit Cost  Unit Price  Shelf Life
count  100.00000  100.000000  100.000000
mean   271.36560  353.256900   91.550000
std    142.59746  187.451692   50.516399
min     21.28000   27.240000    5.000000
25%    138.50250  180.442500   46.000000
50%    265.77000  352.170000   95.500000
75%    405.79000  530.617500  131.000000
max    497.08000  700.600000  178.000000

In [12]:
product.columns.tolist()

['Product ID',
 'Product Name',
 'Category',
 'Subcategory',
 'Unit Cost',
 'Unit Price',
 'Supplier',
 'Shelf Life']

In [5]:
product.isnull().sum()

Product ID      0
Product Name    0
Category        0
Subcategory     0
Unit Cost       0
Unit Price      0
Supplier        0
Shelf Life      0
dtype: int64

In [6]:
product.duplicated().sum()

np.int64(0)

In [7]:
product.nunique()

Product ID      100
Product Name    100
Category          4
Subcategory      12
Unit Cost       100
Unit Price      100
Supplier         10
Shelf Life       81
dtype: int64

In [21]:
product["Product ID"].nunique()

100

In [25]:
product[["Product ID","Product Name"]].drop_duplicates()

   Product ID        Product Name
0    PRD10000       Cheese Item 0
1    PRD10001        Bread Item 1
2    PRD10002  Accessories Item 2
3    PRD10003          Men Item 3
4    PRD10004          Men Item 4
..        ...                 ...
95   PRD10095       Bread Item 95
96   PRD10096       Bread Item 96
97   PRD10097         Men Item 97
98   PRD10098        Milk Item 98
99   PRD10099         Men Item 99

[100 rows x 2 columns]

In [31]:
product[product["Unit Cost"] <= 0].sum()

Product ID
Product Name
Category
Subcategory
Unit Cost       0.0
Unit Price      0.0
Supplier
Shelf Life        0
dtype: object

In [33]:
product[product["Unit Price"] <= 0].sum()

Product ID
Product Name
Category
Subcategory
Unit Cost       0.0
Unit Price      0.0
Supplier
Shelf Life        0
dtype: object

In [35]:
product[product["Unit Price"] < product["Unit Cost"]]

Empty DataFrame
Columns: [Product ID, Product Name, Category, Subcategory, Unit Cost, Unit Price, Supplier, Shelf Life]
Index: []

In [37]:
product["Category"].value_counts()

Category
Apparel        31
Dairy          25
Bakery         22
Electronics    22
Name: count, dtype: int64

In [38]:
product["Subcategory"].value_counts()

Subcategory
Men            16
Yogurt         13
Laptop         10
Bread           9
Kids            9
Cakes           7
Cheese          6
Accessories     6
Cookies         6
Women           6
Mobile          6
Milk            6
Name: count, dtype: int64

In [40]:
product["Supplier"].value_counts()

Supplier
Supplier 8     14
Supplier 10    13
Supplier 3     12
Supplier 5     11
Supplier 4     10
Supplier 2     10
Supplier 7      8
Supplier 9      8
Supplier 6      8
Supplier 1      6
Name: count, dtype: int64

In [42]:
product["Shelf Life"].describe()

count    100.000000
mean      91.550000
std       50.516399
min        5.000000
25%       46.000000
50%       95.500000
75%      131.000000
max      178.000000
Name: Shelf Life, dtype: float64

In [45]:
product[product["Shelf Life"] <=0].sum()

Product ID
Product Name
Category
Subcategory
Unit Cost       0.0
Unit Price      0.0
Supplier
Shelf Life        0
dtype: object

In [8]:
product.columns = product.columns.str.strip()

product["Product Name"] = product["Product Name"].str.strip()

product["Category"] = product["Category"].str.strip()
product["Subcategory"] = product["Subcategory"].str.strip()
product["Supplier"] = product["Supplier"].str.strip()

In [10]:
product.to_csv(
    "../03_Cleaned_Data/Product_Data_Cleaned.csv",index=False
)

## Conclusion

- Dataset contains 100 products.
- No missing values.
- No duplicate records.
- Product IDs are unique.
- Unit Cost and Unit Price are valid.
- Dataset passed all validation checks.

Ready for SQL and Power BI.